### ISSUE TITLE
how do i use this?

### ISSUE THREAD

**Issue by wavvywob** [424778940z/BZH_AO_NO_KISEKI_Savedata_Editor#1]

**Comment by 424778940z** [comment]
Well you have to compile it first.
But just FYI, this is for the older version of the game that released around 2013 in Asia.
It is not for the Xseed port on steam.

**Comment by wavvywob** [comment]
there is no xseed port for ao...

**Comment by 424778940z** [comment]
> there is no xseed port for ao...

I have no idea, never bother to check that lol.
But anyways, you can compile it and try on your game save, btw this editor is not in English.
If you like you may use the address I found to make a new one since this project is really old.
